#!/bin/bash

: ${MYSQL_PORT:=3306}
export MYSQL_PORT

chown -R mysql:mysql /var/run/mysqld /var/lib/mysql

if [ ! -d /var/lib/mysql/mysql ] ; then
    /usr/bin/mysql_install_db
fi

exec /usr/sbin/mysqld \
    --basedir=/usr \
    --datadir=/var/lib/mysql
    --plugin-dir=/usr/lib/mysql/plugin \
    --user=mysql \
    --log-error=/var/log/mysql/error.log \
    --pid-file=/var/run/mysqld/mysqld.pid \
    --socket=/var/run/mysqld/mysqld.sock \
    --port=$MYSQL_PORT
